### ISSUE TITLE
Cannot find this workshop on AAAI-18 webpage

### ISSUE THREAD

**Issue by yuxiang-wu** [nl4se/nl4se.github.io#1]
Thank you for organizing the NL4SE workshop! I am going to attend AAAI-18, and I am really interested in registering this workshop. However, I cannot find it on the [AAAI-18 workshop webpage](https://aaai.org/Conferences/AAAI-18/ws18workshops/). Could you give any more detailed guidance for attending this workshop?

**Comment by devanbu** [comment]
It's W16. Hope to see you soon!

pls xcuse typos. from mobile.

prem.

pls xcuse typos. from mobile.

prem.

**Comment by yuxiang-wu** [comment]
Thank you! See you in New Orleans!
